networks:
  traefik:
    external: true
  uplink:
    internal: false
  email:
    internal: false
  frontend:
    internal: true
  data:
    internal: true

x-default-environment: &default-environment
  ACTION_HOST: backendAction
  ACTION_PORT: "9002"
  AUTH_COOKIE_KEY_FILE: /run/secrets/auth_cookie_key
  AUTH_HOST: auth
  AUTH_PORT: "9004"
  AUTH_TOKEN_KEY_FILE: /run/secrets/auth_token_key
  AUTOUPDATE_HOST: autoupdate
  AUTOUPDATE_PORT: "9012"
  CACHE_HOST: redis
  CACHE_PORT: "6379"
  DATABASE_HOST: postgres
  DATABASE_NAME: openslides
  DATABASE_PASSWORD_FILE: /run/secrets/postgres_password
  DATABASE_PORT: "5432"
  DATABASE_USER: openslides
  DATASTORE_READER_HOST: datastoreReader
  DATASTORE_READER_PORT: "9010"
  DATASTORE_WRITER_HOST: datastoreWriter
  DATASTORE_WRITER_PORT: "9011"
  ICC_HOST: icc
  ICC_PORT: "9007"
  INTERNAL_AUTH_PASSWORD_FILE: /run/secrets/internal_auth_password
  MANAGE_AUTH_PASSWORD_FILE: /run/secrets/manage_auth_password
  MANAGE_HOST: manage
  MANAGE_PORT: "9008"
  MEDIA_DATABASE_HOST: postgres
  MEDIA_DATABASE_NAME: openslides
  MEDIA_DATABASE_PASSWORD_FILE: /run/secrets/postgres_password
  MEDIA_DATABASE_PORT: "5432"
  MEDIA_DATABASE_USER: openslides
  MEDIA_HOST: media
  MEDIA_PORT: "9006"
  MESSAGE_BUS_HOST: redis
  MESSAGE_BUS_PORT: "6379"
  OPENSLIDES_DEVELOPMENT: "false"
  OPENSLIDES_LOGLEVEL: info
  PRESENTER_HOST: backendPresenter
  PRESENTER_PORT: "9003"
  RESTRICTER_URL: http://autoupdate:9012/internal/autoupdate
  SEARCH_HOST: search
  SEARCH_PORT: "9050"
  SUPERADMIN_PASSWORD_FILE: /run/secrets/superadmin
  VOTE_DATABASE_HOST: postgres
  VOTE_DATABASE_NAME: openslides
  VOTE_DATABASE_PASSWORD_FILE: /run/secrets/postgres_password
  VOTE_DATABASE_PORT: "5432"
  VOTE_DATABASE_USER: openslides
  VOTE_HOST: vote
  VOTE_PORT: "9013"

services:
  proxy:
    image: ghcr.io/openslides/openslides/openslides-proxy:latest
    depends_on:
      - client
      - backendAction
      - backendPresenter
      - autoupdate
      - search
      - auth
      - media
      - icc
      - vote
    environment:
      << : *default-environment
      ENABLE_LOCAL_HTTPS: 1
      ENABLE_AUTO_HTTPS: 0
      HTTPS_CERT_FILE: /run/secrets/cert_crt
      HTTPS_KEY_FILE: /run/secrets/cert_key
    networks:
      - uplink
      - traefik # add to traefik network
      - frontend
    # ports:
    #   - 127.0.0.1:8000:8000

    # add labels to connect to traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openslides.rule=Host(`${OPENSLIDES_DOMAIN}`)"
      - "traefik.http.routers.openslides.entrypoints=websecure"
      - "traefik.http.services.openslides.loadbalancer.server.port=8000"
      - "traefik.http.services.openslides.loadbalancer.server.scheme=https"

    secrets:
      - cert_crt
      - cert_key

  client:
    image: ghcr.io/openslides/openslides/openslides-client:latest
    depends_on:
      - backendAction
      - backendPresenter
      - autoupdate
      - search
      - auth
      - media
      - icc
      - vote
    environment:
      << : *default-environment
    networks:
      - frontend

  backendAction:
    image: ghcr.io/openslides/openslides/openslides-backend:latest
    depends_on:
      - datastoreWriter
      - auth
      - media
      - vote
      - postgres
    environment:
      << : *default-environment
      OPENSLIDES_BACKEND_COMPONENT: action
      # OPENSLIDES_LOGLEVEL: debug
      EMAIL_HOST: "${EMAIL_HOST}"
      EMAIL_PORT: "${EMAIL_PORT}"
      EMAIL_HOST_USER: "${EMAIL_HOST_USER}"
      EMAIL_HOST_PASSWORD: '${EMAIL_HOST_PASSWORD}'
      EMAIL_CONNECTION_SECURITY: "${EMAIL_CONNECTION_SECURITY}"
      EMAIL_TIMEOUT: "${EMAIL_TIMEOUT}"
      EMAIL_ACCEPT_SELF_SIGNED_CERTIFICATE: "false"
      DEFAULT_FROM_EMAIL: "${DEFAULT_FROM_EMAIL}"

    networks:
      - frontend
      - data
      - email
    secrets:
      - auth_token_key
      - auth_cookie_key
      - internal_auth_password
      - postgres_password

  backendPresenter:
    image: ghcr.io/openslides/openslides/openslides-backend:latest
    depends_on:
      - auth
      - postgres
    environment:
      << : *default-environment
      OPENSLIDES_BACKEND_COMPONENT: presenter
    networks:
      - frontend
      - data
    secrets:
      - auth_token_key
      - auth_cookie_key
      - postgres_password

  backendManage:
    image: ghcr.io/openslides/openslides/openslides-backend:latest
    depends_on:
      - datastoreWriter
      - postgres
    environment:
      << : *default-environment
      OPENSLIDES_BACKEND_CREATE_INITIAL_DATA: "1"
      OPENSLIDES_BACKEND_COMPONENT: action
    networks:
      - data
      - email
    secrets:
      - auth_token_key
      - auth_cookie_key
      - internal_auth_password
      - postgres_password
      - superadmin

  datastoreReader:
    image: ghcr.io/openslides/openslides/openslides-datastore-reader:latest
    depends_on:
      - postgres
    environment:
      << : *default-environment
      NUM_WORKERS: "8"
    networks:
      - data
    secrets:
      - postgres_password

  datastoreWriter:
    image: ghcr.io/openslides/openslides/openslides-datastore-writer:latest
    depends_on:
      - postgres
      - redis
    environment:
      << : *default-environment
    networks:
      - data
    secrets:
      - postgres_password

  postgres:
    image: postgres:15
    environment:
      << : *default-environment
      POSTGRES_DB: openslides
      POSTGRES_USER: openslides
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    networks:
      - data
    secrets:
      - postgres_password

  autoupdate:
    image: ghcr.io/openslides/openslides/openslides-autoupdate:latest
    depends_on:
      - datastoreReader
      - redis
    environment:
      << : *default-environment
    networks:
      - frontend
      - data
    secrets:
      - auth_token_key
      - auth_cookie_key
      - postgres_password

  search:
    image: ghcr.io/openslides/openslides/openslides-search:latest
    depends_on:
      - datastoreReader
      - postgres
      - autoupdate
    environment:
      << : *default-environment
    networks:
      - frontend
      - data
    secrets:
      - auth_token_key
      - auth_cookie_key
      - postgres_password

  auth:
    image: ghcr.io/openslides/openslides/openslides-auth:latest
    depends_on:
      - datastoreReader
      - redis
    environment:
      << : *default-environment
    networks:
      - frontend
      - data
    secrets:
      - auth_token_key
      - auth_cookie_key
      - internal_auth_password

  vote:
    image: ghcr.io/openslides/openslides/openslides-vote:latest
    depends_on:
      - datastoreReader
      - auth
      - autoupdate
      - redis
    environment:
      << : *default-environment
    networks:
      - frontend
      - data
    secrets:
      - auth_token_key
      - auth_cookie_key
      - postgres_password

  redis:
    image: redis:alpine
    command: redis-server --save ""
    environment:
      << : *default-environment
    networks:
      - data

  media:
    image: ghcr.io/openslides/openslides/openslides-media:latest
    depends_on:
      - postgres
    environment:
      << : *default-environment
    networks:
      - frontend
      - data
    secrets:
      - auth_token_key
      - auth_cookie_key
      - postgres_password

  icc:
    image: ghcr.io/openslides/openslides/openslides-icc:latest
    depends_on:
      - datastoreReader
      - postgres
      - redis
    environment:
      << : *default-environment
    networks:
      - frontend
      - data
    secrets:
      - auth_token_key
      - auth_cookie_key
      - postgres_password

  manage:
    image: ghcr.io/openslides/openslides/openslides-manage:latest
    depends_on:
      - datastoreReader
      - backendManage
    environment:
      << : *default-environment
      ACTION_HOST: backendManage
    networks:
      - frontend
      - data
    secrets:
      - superadmin
      - manage_auth_password
      - internal_auth_password

  autologin:
    build: ./autologin
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openslides-autologin.rule=Host(`${OPENSLIDES_DOMAIN}`) && PathPrefix(`/autologin`)"
      - "traefik.http.routers.openslides-autologin.entrypoints=websecure"
      - "traefik.http.services.openslides-autologin.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.openslides-autologin-strip.stripprefix.prefixes=/autologin"
      - "traefik.http.routers.openslides-autologin.middlewares=openslides-autologin-strip"

secrets:
  auth_token_key:
    file: ./secrets/auth_token_key
  auth_cookie_key:
    file: ./secrets/auth_cookie_key
  superadmin:
    file: ./secrets/superadmin
  manage_auth_password:
    file: ./secrets/manage_auth_password
  internal_auth_password:
    file: ./secrets/internal_auth_password
  postgres_password:
    file: ./secrets/postgres_password
  cert_crt:
    file: ./secrets/cert_crt
  cert_key:
    file: ./secrets/cert_key
